# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
default: &default
  admins: <%= ENV['ADMINS'] %>
  default_admin_password: <%= ENV['DEFAULT_PASSWORD'] %>
  user:
    email: <%= ENV['TEST_USER_EMAIL'] %>
    password: <%= ENV['TEST_USER_PASSWORD'] %>

development:
  <<: *default
  secret_key_base: 313eb3649ce0435adccd5ebdbb65d6fa5bb5150a7e6d0e05342edb1899f86eb5fefd4a4fc4a666d3c3ac518f93ff39da522ebf24d72f071b1f34d15529b1bc35

test:
  <<: *default
  secret_key_base: 313eb3649ce0435adccd5ebdbb65d6fa5bb5150a7e6d0e05342edb1899f86eb5fefd4a4fc4a666d3c3ac518f93ff39da522ebf24d72f071b1f34d15529b1bc35

production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
